/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { Migrations, MigrationsInterface } from "../Migrations.js";

  const _abi = [
  {
    "inputs": [],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "last_completed_migration",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "completed",
        "type": "uint256"
      }
    ],
    "name": "setCompleted",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b50335f5f6101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555061023b8061005b5f395ff3fe608060405234801561000f575f5ffd5b506004361061003f575f3560e01c8063445df0ac146100435780638da5cb5b14610061578063fdacd5761461007f575b5f5ffd5b61004b61009b565b604051610058919061013b565b60405180910390f35b6100696100a1565b6040516100769190610193565b60405180910390f35b610099600480360381019061009491906101da565b6100c5565b005b60015481565b5f5f9054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b5f5f9054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff160361012057806001819055505b50565b5f819050919050565b61013581610123565b82525050565b5f60208201905061014e5f83018461012c565b92915050565b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f61017d82610154565b9050919050565b61018d81610173565b82525050565b5f6020820190506101a65f830184610184565b92915050565b5f5ffd5b6101b981610123565b81146101c3575f5ffd5b50565b5f813590506101d4816101b0565b92915050565b5f602082840312156101ef576101ee6101ac565b5b5f6101fc848285016101c6565b9150509291505056fea264697066735822122081d8cbdea3e6b093138ba344c82bb995c018146fc950ef02c0fb9a955b45e39664736f6c634300081c0033";

  
      type MigrationsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MigrationsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Migrations__factory extends ContractFactory {
    
      constructor(...args: MigrationsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Migrations & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Migrations__factory {
      return super.connect(runner) as Migrations__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MigrationsInterface {
      return new Interface(_abi) as MigrationsInterface;
    }
    
    override attach(address: string | Addressable): Migrations {
      return super.attach(address) as Migrations;
    }
  static connect(address: string, runner?: ContractRunner | null): Migrations {
      return new Contract(address, _abi, runner) as unknown as Migrations;
    }
  }

  
  